[package]
authors = ["Michał Budzyński <m.budzynski@samsung.com>"]
name = "test_pulls"
version = "0.1.0"
[dependencies]
error-chain = "*"
hyper = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"

[dependencies.chrono]
features = ["serde"]
version = "0.4"
